apiVersion: apps/v1
kind: Deployment
metadata:
  name: afklm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: afklm
  template:
    metadata:
      labels:
        app: afklm
    spec:
      containers:
      - name: afklm
        image: acrakflm.azurecr.io/afdemoapp
        ports:
        - containerPort: 8080
        env:
        - name: COSMOSDB__DB_URL
          value: "#{DB_URL}#"
        - name: COSMOSDB__DB_SECRET
          value: "#{DB_SECRET}#"
---
apiVersion: v1
kind: Service
metadata:
  name: cosmos-todo-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: afklm
  type: LoadBalancer
